### ISSUE TITLE
onItemClick event 

### ISSUE THREAD

**Issue by abelski21** [afconsult/quill-mention#10]
Is there a way I could overwrite or disable the onClick event of the render list item? I'm doing some validations in the mention list items, and some of those shouldn't be inserted to the editor. Is this possible without modifying the plugin?

**Comment by MadSpindel** [comment]
Not possible now but it is possible to make it as an option (like renderItem: https://github.com/afconsult/quill-mention/blob/master/src/quill.mention.js#L19)

Not sure if I have the time to change the code. Maybe you can make a pull request?

**Comment by abelski21** [comment]
Okay thanks, I'll try to push something today @MadSpindel

**Comment by abelski21** [comment]
Added pull request [here](https://github.com/afconsult/quill-mention/pull/11). So instead of overwriting the onItemClicked behavior, I figure that it only needs a boolean option to not call the selectItem().
