### ISSUE TITLE
Question / Idea: change of a trigger symbol

### ISSUE THREAD

**Issue by wlecki** [afconsult/quill-mention#12]
Hi,

Thanks for this great module.
Is it possible to easily change the trigger symbol from '@' to e.g. '#'?

**Comment by MadSpindel** [comment]
Not possible today. But I know @cwhite-connectfirst is working on a fork with support for multiple trigger symbols so it's probably something coming soon.

**Comment by etyp** [comment]
+1 to this. @cwhite-connectfirst do you plan to submit a PR for the `mentionDenotationChars` option or are you keeping the fork separate?

**Comment by cwhite-connectfirst** [comment]
I'd be happy to submit a PR. Do you guys have any guidelines for contributions?

**Comment by MadSpindel** [comment]
@cwhite-connectfirst Nope, not yet but I guess I should look into it in the future. Feel free to submit a PR! 👍

**Comment by cwhite-connectfirst** [comment]
https://github.com/afconsult/quill-mention/pull/13 PR is here
