### ISSUE TITLE
Do not automatically insert a space after mention

### ISSUE THREAD

**Issue by Poitrin** [afconsult/quill-mention#15]
It would be nice to have an option which disables the automatic insertion of a space after a mention, thanks!

**Comment by MadSpindel** [comment]
Yes, or maybe it should only remove it in some cases? Let's say I mention someone and then types letter !. or , - it should remove the space after mention.

**Comment by rosswilson252** [comment]
Would this be a straightforward removal of the space or should it be a config value for now so that a breaking change isn't introduced (i.e. `spaceAfterInsert: false`)?
