### ISSUE TITLE
How to insert as plain text

### ISSUE THREAD

**Issue by essivision** [afconsult/quill-mention#18]
Hi,
I wanna to insert key like `@requester` as plain text. Do you have any option for this? Already when I export text from `Quilljs` it's return:

```
<span class="mention" data-id="1" data-value="Request" data-denotation-char="@">﻿<span contenteditable="false"><span class="ql-mention-denotation-char">@</span>Request</span>﻿</span> </p>
```

I wanna to see in export this:
```
@Request
```

**Comment by MadSpindel** [comment]
How do you export? Sounds like you want it as plain text without html? Have you tried quill.getText()?
https://quilljs.com/docs/api/#gettext

**Comment by essivision** [comment]
In php I use it for solve problem
```
$html = preg_replace('#<h3 class="hdr">(.*?)</h3>#', '', $html);
```

and javascript
[https://stackoverflow.com/questions/822452/strip-html-from-text-javascript](https://stackoverflow.com/questions/822452/strip-html-from-text-javascript)
