### ISSUE TITLE
Callback to get the value of selected mentions

### ISSUE THREAD

**Issue by sebastian-walter** [afconsult/quill-mention#21]
Hi there,

I am using this library together with vue2-editor. I am wondering if there is some callback function I could use to get the selected mentions.

Otherwise I would have to parse the content and extract the mentions myself or am I missing something here?

Thanks a lot!
Sebastian

**Comment by MadSpindel** [comment]
Hi,

You should use quill.getContents() and parse the content for mentions:
https://quilljs.com/docs/api/#getcontents
