### ISSUE TITLE
Upper limit on number of items shown in the dropdown

### ISSUE THREAD

**Issue by suparnavg** [afconsult/quill-mention#23]
Would it be possible to expose a parameter like maxItems (for example like in the [angular-mentions](https://github.com/dmacfarlane/angular-mentions) module) that limits the number of items in the dropdown?

The use case I have in mind is 20+ possible mention values, of which only the first maxItems values will be displayed as soon as the user types "#"

**Comment by MadSpindel** [comment]
You can achieve this in the source callback before calling the renderList function. Just use plain Javascript and limit it to as many as you want.

**Comment by suparnavg** [comment]
Thanks for the tip!
