### ISSUE TITLE
Dropdown goes off screen when at the bottom of page

### ISSUE THREAD

**Issue by eltimn** [afconsult/quill-mention#3]
I'm afraid the mention list is still dropping down when at the bottom of the page. Here is a screenshot of the demo page with editor 2 at the bottom of the page:

![screenshot from 2018-02-12 14-36-45](https://user-images.githubusercontent.com/103936/36118479-cd2b8e4a-1002-11e8-8cd5-5ed5416cecd7.png)

The list goes off the screen so you can't see it.

**Comment by MadSpindel** [comment]
Yeah, I am note sure why because if you do like this it will work:
![bottom](https://user-images.githubusercontent.com/3159565/36138638-7786f3b0-109a-11e8-9475-e12fb9525de7.gif)

**Comment by MadSpindel** [comment]
Found the bug. I didn't check the correct window values. It should work now.

**Comment by eltimn** [comment]
:+1:   Works now. Thanks again.
