### ISSUE TITLE
selection callback

### ISSUE THREAD

**Issue by Usama-Ibex** [afconsult/quill-mention#49]
it's possible when i call select and get data through callback?

**Comment by josepepe91** [comment]
how can I get the complete list of mentions and the new mention?

**Comment by stefan-falk** [comment]
@josepepe91 Idk if there is an easier way but you could try to use `getContents()` (see https://github.com/afconsult/quill-mention/issues/52). There you'll find objects which may or may not have a `mention` attribute.

**Comment by silentsnooc** [comment]
I created a PR for a different purpose but it would cover this issue as well (see `beforeInsert()`) in https://github.com/afconsult/quill-mention/pull/56

**Comment by josepepe91** [comment]
Thanks, I finally use delta, with debounce time in the event onContentChanged.
