### ISSUE TITLE
Serializing content to markup

### ISSUE THREAD

**Issue by silentsnooc** [afconsult/quill-mention#52]
This might probably end up as a feature request but is there a way I can serialize the content in the editor? What I need basically is to transform the content of the editor to a simpler format (e.g. a markup) s.t. in the end there is only the text and the mentioned entity in form of a markup available.

```html
<div><div data-id="1" data-value="Brad"><span>Brad</span></div> came to the office</div>
```
would become something like
``` 
{id:1} came to the office
```

Is there a "*simple*" I could do this myself with the existing API?

**Comment by MadSpindel** [comment]
Maybe that something you can achieve with Quill Delta objects?

https://quilljs.com/docs/api/#getcontents
https://quilljs.com/docs/delta/

**Comment by silentsnooc** [comment]
@MadSpindel omg that's it. You have no idea how long I was searching for a simple solution like that. It looks like that `getContents()` gives you a list, which is already *in order* (if I'm not mistaken) from which you can serialize the content with a brutally simple function!

This is awesome! Thanks man!

**Comment by MadSpindel** [comment]
Good to hear 👍

**Comment by josepepe91** [comment]
Thanks, I finally use delta
