### ISSUE TITLE
How to run the demo?

### ISSUE THREAD

**Issue by silentsnooc** [afconsult/quill-mention#55]
I'd like to work on `quill-mention` but I am not really able to run the demo locally.

I've installed `http-server` (via `npm`) and try to serve the static files but I am running from one exception into the next one.

I assume I am doing it wrong so what's the fastest way to get the demo running s.t. I can add some features?

First thing I noticed btw is that the paths seem to be wrong:

```html
<link href="quill.mention.min.css" rel="stylesheet">
<script src="quill.mention.min.js"></script>
```
----
Btw I've created a [ `quill-mention` ](https://stackoverflow.com/questions/tagged/quill-mention) tag on stackoverflow

**Comment by MadSpindel** [comment]
The best way is to use yarn (https://yarnpkg.com/lang/en/).

Just checkout the git repo, run `yarn install` and when it have installed all dependencies, you run `yarn start`

**Comment by silentsnooc** [comment]
Wow I could laugh my ass off if it wasn't so sad that I just did this:

```
npm install
yarn start
```
and it worked ..
