### ISSUE TITLE
The given range isn't in document. - when used with react-quill

### ISSUE THREAD

**Issue by AbhimanyuG** [afconsult/quill-mention#68]
Nothing to configure - used default options.

**Comment by AbhimanyuG** [comment]
Not this library's issue.

**Comment by nichwch** [comment]
what was the issue? I'm having the same bug

**Comment by mateioprea** [comment]
@nichwch put the mention plugin above your React Component. This will do the trick. 

```javascript
const mention = {
...
}

export default class YourComponent extends Component {

	render() {
		return (
			<ReactQuill
				modules={{mention}}
			/>
		)
	}
}
```

**Comment by MedAdrian** [comment]
@mateioprea what if I need to dispatch an ajax request from the props, a.k.a. `this.props.dispatch()` how can I do this outside the class?
