### ISSUE TITLE
Focus on highlighted list item

### ISSUE THREAD

**Issue by abelski21** [afconsult/quill-mention#7]
Hi, I'm trying to focus on the highlighted list item when pressing the down or up arrow key. I use to have a long list of users to mention and I want to auto scroll the list down next to the highlighted item. I've tried to add this quill keyboard handler for down arrow but it didn't work:
```
down: {
        key: 40,
        handler: function(range: any, context: any) {      
          const mentionListItem: any = document.querySelector('.ql-mention-list-item.selected');
          const focusList: any = findDOMNode(mentionListItem).nextSibling;
          // TODO: know how to focus list item
          mentionListItem.focus();
          return true;
        }
      }
```

I guess because we already return false to the downHandler function of quill-mention module? Is there a way we focus the item to scroll it down to the remaining items of the list? Like in this [example](http://jsfiddle.net/38zR3/42/) .

**Comment by MadSpindel** [comment]
You need to set the correct scrollTop value on the ql-mention-list-container.

**Comment by abelski21** [comment]
Thank you for the response @MadSpindel but when should I set this property?

**Comment by MadSpindel** [comment]
I think the best way is to make a pull request. So probably in [highlightItem()](https://github.com/afconsult/quill-mention/blob/master/src/quill.mention.js#L112) you need to check if its scrollable and then set the correct scrollTop value on this.mentionContainer

**Comment by abelski21** [comment]
Okay, I'll try to push a PR today. Thanks!

**Comment by abelski21** [comment]
@MadSpindel I already have updates in my local but I can't seem to push a branch in this repo. I'm getting a permission denied.

**Comment by MadSpindel** [comment]
@abelski21 You need to fork the branch first. Then you need to make a pull request from your branch to this master branch.

**Comment by abelski21** [comment]
Got it. Thanks! Here's my pull request #8
