### ISSUE TITLE
@mention does not show user image on li list

### ISSUE THREAD

**Issue by yosoul93** [afconsult/quill-mention#73]
This feature is very important, on renderList function, you created li list tags on ngfor loop, can we create img tags and append it to li list tags?

const li = document.createElement('li');
const img = document.createElement('img');
img.src = data[i].avatar;
li.appendChild(img)

**Comment by silentsnooc** [comment]
Did you take a look at `renderItem`? Should be no problem to render what you want. It should look something like this:

```javascript
renderItem: (item, searchTerm) => {
  return `
    <div class="cql-list-item-inner">
      <img src="${item.imageUrl}">
      ${item.value}
    </div>`;
}
```

**Comment by a-utkarsh** [comment]
can you write full example. I am not able to render custom HTML. I am using MUI Listitem 
`allowedChars           : /^[A-Za-z\sÅÄÖåäö]*$/,
		mentionDenotationChars : ["@", "#"],
		isolateCharacter       : true, 
		renderItem             : function (item, searchTerm) {
			return (
				<ListItem value = {item.id}> 
					<ListItemAvatar>
						<Avatar> UA </Avatar>
					</ListItemAvatar>
					<ListItemText primary = {item.value} />
				</ListItem>
			);
		}, 
		source                 : function (searchTerm, renderItem, mentionChar) {
			let values;
			if (mentionChar === "@") {
				values = atValues;
			}
			if (searchTerm.length === 0) {
				renderItem(values, searchTerm);
			} else {
				const matches = [];
				for (let i = 0; i < values.length; i++)
					if (
						~values[i].value.toLowerCase().indexOf(searchTerm.toLowerCase())
					)
						matches.push(values[i]);
				renderItem(matches, searchTerm);
			}
		}`

**Comment by Zayyarhein** [comment]
`allowedChars : /^[A-Za-z\sÅÄÖåäö]*$/, mentionDenotationChars : ["@", "#"], isolateCharacter : true, renderItem : function (item, searchTerm) { return ( <ListItem value = {item.id}> <ListItemAvatar> <Avatar> UA </Avatar> </ListItemAvatar> <ListItemText primary = {item.value} /> </ListItem> ); }, source : function (searchTerm, renderItem, mentionChar) { let values; if (mentionChar === "@") { values = atValues; } if (searchTerm.length === 0) { renderItem(values, searchTerm); } else { const matches = []; for (let i = 0; i < values.length; i++) if ( ~values[i].value.toLowerCase().indexOf(searchTerm.toLowerCase()) ) matches.push(values[i]); renderItem(matches, searchTerm); } }`
How about this problem? Can you show the user image in li list? If you found the any solution, please let me known your solution for this case. @a-utkarsh

**Comment by Eduser-vivo** [comment]
import { renderToString } from 'react-dom/server'

const renderMentionItem = (item) =>{

return (
    <ListItem value = {item.id}> 
        <ListItemAvatar> 
            <MAvatar
                src={item.avatar}
                alt={item.value}
                color={createAvatar(item.value).color}
                sx={{ width: 27, height: 27, fontSize: 12 }}
            >
                {createAvatar(item.value).name}
            </MAvatar>
        </ListItemAvatar>
        <ListItemText primary = {item.value} />
    </ListItem> 
    );
}

renderItem : function(item, searchTerm){ return renderToString(renderMentionItem(item)) },
