### ISSUE TITLE
Question: Event on deletion?

### ISSUE THREAD

**Issue by mann-david** [afconsult/quill-mention#79]
I need to maintain an list of @mentioned people outside of the editor.  I can hook the `selected` event to add a person to that list, but I can't figure out any way to remove people from the external list when their @mention is deleted from the editor.

Am I missing something?

Thx.

**Comment by fzuellich** [comment]
@mann-david I believe you are not missing something. quill-mention doesn't offer a hook/callback to check for removed mentions. Have you considered parsing the final Quill Delta? You can convert it to JSON and then check for the Mention parts. This way you can create a diff. Works great on the backend-part, too.

**Comment by silentsnooc** [comment]
I am at the point where I'd require this feature too.
@MadSpindel Any chance we can get that kind of feature?

**Comment by MadSpindel** [comment]
I believe you will have to make a diff as @fzuellich are suggesting. I don't think Quill have any event for deleting blots.

**Comment by silentsnooc** [comment]
@MadSpindel You're right I guess. Just went for a diff. It's pretty straight forward.

**Comment by iamshouvikmitra** [comment]
Hey @silentsnooc, can you provide an implementation for the same?

**Comment by nasirmovlamov** [comment]
is there any update about this situation ? Because i also need help about this situation

**Comment by ziaulrehman40** [comment]
need some fix

**Comment by ziaulrehman40** [comment]
#216 is a duplicate, don't know why this one was closed
