### ISSUE TITLE
How to append quill-mention dropdown to body?

### ISSUE THREAD

**Issue by jayaramasaipavanmanda** [afconsult/quill-mention#81]

**Comment by keyone2693** [comment]
same issue here is there any fix for this ?


![image](https://user-images.githubusercontent.com/19763704/213860218-e68ae873-8355-427a-b73e-8fb19558bc33.png)

i used this but didn't change anything


![image](https://user-images.githubusercontent.com/19763704/213860258-ae42b727-c386-4987-bf54-d89db549f788.png)
