### ISSUE TITLE
issue with mentioned value

### ISSUE THREAD

**Issue by hemanth8888** [afconsult/quill-mention#95]
Hai, I have come across quill and its pretty awesome. i am using it for angular application and my issue is while using #quill-mention with '@' after selection any value i am pushing that value into an array. if user remove mentioned value using back space or delete button hoe can i pop that value from array
thanks in advance

**Comment by MadSpindel** [comment]
You can get the delta with [quill.getContents();](https://quilljs.com/docs/api/#getcontents). So you should watch the delta which will always have the correct mentions.

**Comment by hemanth8888** [comment]
i am Using it in angular and i am not able to use able to use getContents() api
