### ISSUE TITLE
data-value bug?

### ISSUE THREAD

**Issue by neobie** [afconsult/quill-mention#99]
When looking at the HTML code generated, the data-value would be as below:
`data-value="<a href="http://www.josierice.com" target=_blank>Josie Rice"`

Is this a bug ?

**Comment by davidwinter** [comment]
@MadSpindel I've also encountered this, as it's breaking when trying to render back content. There appears to be a missing closing tag `</a>`, and also, the target value should be quoted too.

Besides that - shouldn't the value also be HTML encoded? 

Happy to provide a pull request fix - but just wanted to check if you closed this for a reason?

**Comment by getreworked** [comment]
@neobie @davidwinter I've just encountered this. Did either of you resolve the issue? I would have expected the `data-value` to just be the string and not include any html.
